<a href="https://colab.research.google.com/github/MarkClarenceRodriguez/58013_Linear_Algebra/blob/main/Determinant_ofMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
A = np.array([[4,7,8],[-9,0,0],[2,3,4]])
print(A)
round(np.linalg.det(A))

[[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]


36

In [8]:
import numpy as np
A = np.array([[2,3,-5],[7,1,-2],[-3,4,1]])
print(A)
round(np.linalg.det(A))

[[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]


-140

PRACTICE MATRIX

In [11]:
import numpy as np
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
round(np.linalg.det(A))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


-14