<a href="https://colab.research.google.com/github/MarkClarenceRodriguez/58013_Linear_Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  Problem 1.  Consider the four matrices, (20 points each)

In [30]:
#a. AB
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

AB = np.dot(A, B)

print("a. AB\n")
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix AB (Product of A and B):")
print(AB)


#b. D + D
import numpy as np


D = np.array([[1, 2],
              [3, 4]])

result = D + D

print("\nb. D + D")
print("\nMatrix D:")
print(D)
print("\nMatrix D + D:")
print(result)

#c. 2C
import numpy as np

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = 2 * C

print("\n c. 2C\n")
print("Matrix C:")
print(C)
print("\n2 * C:")
print(result)





a. AB

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[1 2]
 [3 4]
 [5 6]]

Matrix AB (Product of A and B):
[[22 28]
 [49 64]]

b. D + D

Matrix D:
[[1 2]
 [3 4]]

Matrix D + D:
[[2 4]
 [6 8]]

 c. 2C

Matrix C:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2 * C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2. Find the cross-product of matrices, A = [2,7,4] and
B = [3,9,8]. Show your solutions using Python program .  (40 points)



In [29]:
import numpy as np

A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

cross_product = np.cross(A, B)

print("Matrix A:", A)
print("Matrix B:", B)
print("Cross Product:", cross_product)


Matrix A: [2 7 4]
Matrix B: [3 9 8]
Cross Product: [20 -4 -3]
