<a href="https://colab.research.google.com/github/MarkClarenceRodriguez/58013_Linear_Algebra/blob/main/Vector%2CSpaces%2CandOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
A= np.array([4,3])
B= np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


Checking Shapes
Slide Dimension, Size

In [19]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
#ball = np.shape([[ball1],[ball2]])
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball+balls
print(z)


[1 2 3]
[ 0  1 -1]
(3, 3)


Addition

In [26]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
R = np.add(A,B)
print(R)
print(A+B)

[ 6 -2]
[ 6 -2]


Subtraction



In [29]:
R1=np.subtract(A,B)
print(R1)
R2=np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


Scalar Product  

In [30]:
S = np.array ([2])
V = S*A
print(V)

[8 6]


Dot Product

In [42]:
A = ([4,3])
B = ([2,-5])
R= np.dot(A,B)
print(R)

-7


Property of matrix

In [57]:
#Identity Matrix
c = np.eye(3,3)
print(c)

#Zero Matrix
d = np.zeros([5,5])
print(d)

#Full Matrix
e = np.full((3,3),7)
print(e)

#Transpose Matrix
f= np.transpose(A)
print(f)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
